install:
  - cup gitversion.portable -pre -y

version: '{build}'

image: 'Visual Studio 2017'

branches:
  only:
    - master

only_commits:
  message: /\+semver:/

environment:
  APPVEYOR_NUGET_API_KEY:
    secure: AtKUh7VTiq0BCPftMVX+nkY7Jsz47iYsYR2iWJ3U//cAQwvo0MWuY0A0bbY3kP4L
  APPVEYOR_PERSONAL_ACCESS_TOKEN:
    secure: +823CdXZbrvfhBVAbcsRT/CGVmREYmkH5g5TC8+1HWjGt0SHZtgS4AWVBbeyfzLl
  APPVEYOR_GITHUB_USERNAME: 'EsOsO'
  APPVEYOR_GITHUB_EMAIL:
    secure: qOw7foLVABiwY5Y4Th58VNI8sbyJpNwvkFSI9DFxqII=

before_build:
  - ps: C:\ProgramData\chocolatey\bin\gitversion.exe /l console /output buildserver

build_script:
  - ps: . .\build.ps1

test: false

deploy:
  tag: $(ReleaseVersion)
  description: $(ReleaseDescription)
  force_update: true
  draft: false
  prerelease: false
  provider: GitHub
  auth_token:
    secure: +823CdXZbrvfhBVAbcsRT/CGVmREYmkH5g5TC8+1HWjGt0SHZtgS4AWVBbeyfzLl
