image: WMF 5
skip_commits:
  message: /updated readme.*|update readme.*s/
build: false

environment:
  APPVEYOR_NUGET_API_KEY:
    secure: AtKUh7VTiq0BCPftMVX+nkY7Jsz47iYsYR2iWJ3U//cAQwvo0MWuY0A0bbY3kP4L

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module Pester -MinimumVersion 3.4.0 -Scope CurrentUser -Force | Out-Null
      Install-Module psake -Scope CurrentUser -Force | Out-Null
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force | Out-Null
      Install-Module platyPS -Scope CurrentUser -Force | Out-Null

test_script:
  - ps: . .\build.ps1
