image: 'WMF 5'
skip_tags: true
branches:
  only:
    - master
skip_commits:
  message: /updated readme.*|update readme.*s/
build: false

environment:
  APPVEYOR_NUGET_API_KEY:
    secure: AtKUh7VTiq0BCPftMVX+nkY7Jsz47iYsYR2iWJ3U//cAQwvo0MWuY0A0bbY3kP4L
  access_token:
    secure: +823CdXZbrvfhBVAbcsRT/CGVmREYmkH5g5TC8+1HWjGt0SHZtgS4AWVBbeyfzLl
  email:
    secure: qOw7foLVABiwY5Y4Th58VNI8sbyJpNwvkFSI9DFxqII=

test_script:
  - ps: . .\build.ps1
