name: $(rev:r)
trigger:
  branches:
    include:
      - 'azure-pipelines'

jobs:
  - job: Build_PS_Win2016
    pool:
      vmImage: vs2017-win2016

    steps:
      - checkout: self
        persistCredentials: true

      - powershell: |
          cup -y gitversion.portable
        displayName: 'Updating GitVersion'

      - powershell: |
          gitversion.exe /l console /output buildserver
        displayName: 'Getting semver from GitVersion'

      - powershell: |
          .\psake.ps1 -TaskList Test -Verbose
        displayName: 'Execute Tests'
        env:
          azureApplicationId: $(azureApplicationId)
          azureApplicationPassword: $(azureApplicationPassword)
          azureSubscriptionId: $(azureSubscriptionId)
          azureTenantId: $(azureTenantId)
          githubRepoToken: $(githubRepoToken)

      - task: PublishTestResults@2
        inputs:
          testRunner: 'NUnit'
          testResultsFiles: '**/TestResults.unit.xml'
          testRunTitle: 'PS_Win2016_Unit'
        displayName: 'Publish Test Results'
        condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed')

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'jaCoCo'
          summaryFileLocation: '**/CodeCoverage.xml'
          failIfCoverageEmpty: true
        displayName: 'Publish Test Code Coverage'
        condition: and(in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed'), eq(variables['System.PullRequest.IsFork'], false))
