site_name: Powershell Logging Module Documentation
site_description: Powershell Logging Module
site_author: Massimo Bonvicini
repo_url: https://github.com/EsOsO/Logging
edit_uri: edit/master/docs/
copyright: "Powershell Logging Module is licensed under the <a href="https://github.com/EsOsO/Logging/raw/master/LICENSE">MIT license</a>"
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - powershell
nav:
  - Home: index.md
  - Usage: Usage.md
  - 'Available Targets': AvailableTargets.md
  - About:
    - Changelog: CHANGELOG.md
    - Contributing: CONTRIBUTING.md
    - License: LICENSE
